#ZoneMap = {
#    1: {
#        "name": "旧都列车",
#        "level": {1: "外围", 2: "前线", 3: "内部", 4: "腹地", 5: "核心"},
#    },
#    2: {
#        "name": "施工废墟",
#        "level": {1: "前线", 2: "内部", 3: "腹地", 4: "核心"},
#    },
#}
targetMap:
    level: 1 # 默认区域 1: 旧都列车 当前仅支持 1: 旧都列车
    zone: 1 # 默认等级 1: 外围  当前仅支持 1: 外围
wholeCourse: false # 是否打完全程
maxMapTime: 150 # 最大战斗时间
maxFightTime: 900 # 在地图内最大时间