#ZoneMap = {
#    1: {
#        "name": "旧都列车",
#        "level": {1: "外围", 2: "前线", 3: "内部", 4: "腹地", 5: "核心"},
#    },
#    2: {
#        "name": "施工废墟",
#        "level": {1: "前线", 2: "内部", 3: "腹地", 4: "核心"},
#    },
#}

# 模型训练集大部分来自旧都列车，脚本刷图目前旧都列车最稳定，其他图bug会比较多，刷零号业绩旧都列车前线最快，练度够可以直接刷前线
targetMap:
    level: 1                # 默认等级 1: 外围
    zone: 1                 # 默认区域 1: 旧都列车
wholeCourse: False          # 是否打完全程，默认False。           说明： 参数为False，拿完零号业绩会退出战斗，参数为True，拿完零号业绩会继续刷图，直至打完boss
maxFightTime: 150           # 最大战斗时间，单场战斗时间默认为150s，超过150s会重开(部分战斗场景需要跑图，目前还没进行相关处理，遇到这种情况会退掉重开)
maxMapTime: 900             # 在地图内最大时间默认为900s，超过最大时间未通关地图会重开
useGpu: True                # 是否使用GPU，默认True, 使用GPU会加速模型训练,如果改为False，会强制使用CPU进行OCR识别
fightStyle: default         # 战斗风格，默认default，可选ellen（艾莲）